name: unit-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Init submodules
      run: |
        git submodule update --init
    
    - name: Install dependency
      run: |
        sudo apt install graphviz gcovr

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Change to your preferred version

    - name: Run unit-test
      run: |
        ./run_unit_test.py

    - name: Upload to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: unit_test_report/coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}
    
